[package]
name = "adr-to-html"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.21"
markdown = "1.0.0-alpha.16"
fs_extra = "1.3.0"
